"""Initial_migration_with_manufacturing_date

Revision ID: bc66d9a34d1e
Revises: 
Create Date: 2026-02-05 00:14:56.702292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc66d9a34d1e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('business_number', sa.String(length=20), nullable=True),
    sa.Column('client_type', sa.String(length=50), nullable=True),
    sa.Column('ceo_name', sa.String(length=50), nullable=True),
    sa.Column('manager_name', sa.String(length=50), nullable=True),
    sa.Column('fax', sa.String(length=20), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('change_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finished_product_coa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('semi_mfg_date', sa.Date(), nullable=True),
    sa.Column('semi_lot_no', sa.String(length=100), nullable=True),
    sa.Column('pack_date', sa.Date(), nullable=True),
    sa.Column('finished_lot_no', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('unit_volume_ml', sa.Float(), nullable=True),
    sa.Column('sampling_method', sa.String(length=255), nullable=True),
    sa.Column('test_date', sa.Date(), nullable=True),
    sa.Column('examiner', sa.String(length=100), nullable=True),
    sa.Column('reviewer', sa.String(length=100), nullable=True),
    sa.Column('overall_result', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('type_code', sa.String(length=100), nullable=True),
    sa.Column('functional_type_code', sa.String(length=100), nullable=True),
    sa.Column('functional_code', sa.String(length=100), nullable=True),
    sa.Column('usage', sa.String(length=255), nullable=True),
    sa.Column('custom_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_code_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('code_type', sa.String(length=50), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=True),
    sa.Column('year_format', sa.String(length=10), nullable=True),
    sa.Column('separator', sa.String(length=5), nullable=True),
    sa.Column('sequence_length', sa.Integer(), nullable=True),
    sa.Column('current_sequence', sa.Integer(), nullable=True),
    sa.Column('suffix', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_type')
    )
    op.create_table('semi_finished_coa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('lot_no', sa.String(length=100), nullable=True),
    sa.Column('manufacture_date', sa.Date(), nullable=True),
    sa.Column('test_date', sa.Date(), nullable=True),
    sa.Column('examiner', sa.String(length=100), nullable=True),
    sa.Column('overall_result', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('real_name', sa.String(length=50), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('manager_code', sa.String(length=50), nullable=True),
    sa.Column('contact', sa.String(length=20), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('change_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('remember_id', sa.Boolean(), nullable=True),
    sa.Column('auto_login', sa.Boolean(), nullable=True),
    sa.Column('force_password_change', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manager_code'),
    sa.UniqueConstraint('username')
    )
    op.create_table('deletion_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('target_table', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('target_summary', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('backup_data', sa.Text(), nullable=True),
    sa.Column('processed_by_id', sa.Integer(), nullable=True),
    sa.Column('admin_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['processed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finished_product_coa_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=50), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.Column('spec', sa.String(length=255), nullable=True),
    sa.Column('result', sa.String(length=255), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['header_id'], ['finished_product_coa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_name', sa.String(length=255), nullable=False),
    sa.Column('experiment_date', sa.String(length=20), nullable=True),
    sa.Column('manufacturing_date', sa.String(length=20), nullable=True),
    sa.Column('manager_name', sa.String(length=50), nullable=True),
    sa.Column('manager_code', sa.String(length=50), nullable=True),
    sa.Column('lab_no', sa.String(length=50), nullable=True),
    sa.Column('revision', sa.String(length=50), nullable=True),
    sa.Column('experiment_ph_initial', sa.String(length=20), nullable=True),
    sa.Column('experiment_ph_next_day', sa.String(length=20), nullable=True),
    sa.Column('experiment_viscosity_initial', sa.String(length=20), nullable=True),
    sa.Column('experiment_viscosity_next_day', sa.String(length=20), nullable=True),
    sa.Column('experiment_machine', sa.String(length=255), nullable=True),
    sa.Column('experiment_comment', sa.Text(), nullable=True),
    sa.Column('has_target_info', sa.Boolean(), nullable=True),
    sa.Column('target_sample_name', sa.String(length=255), nullable=True),
    sa.Column('target_ph_initial', sa.String(length=20), nullable=True),
    sa.Column('target_ph_next_day', sa.String(length=20), nullable=True),
    sa.Column('target_viscosity_initial', sa.String(length=20), nullable=True),
    sa.Column('target_viscosity_next_day', sa.String(length=20), nullable=True),
    sa.Column('target_machine', sa.String(length=255), nullable=True),
    sa.Column('target_client_id', sa.String(length=255), nullable=True),
    sa.Column('oem_odm_client_id', sa.Integer(), nullable=True),
    sa.Column('change_log', sa.Text(), nullable=True),
    sa.Column('sample_sent_count', sa.Integer(), nullable=True),
    sa.Column('sample_delivery_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['oem_odm_client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient_report_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('ingredient_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['ingredient_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('origin', sa.String(length=100), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('package_unit', sa.String(length=50), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('hs_code', sa.String(length=50), nullable=True),
    sa.Column('nmpa_reg_num', sa.String(length=100), nullable=True),
    sa.Column('reg_date', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('change_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('semi_finished_coa_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=False),
    sa.Column('seq_no', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.Column('spec', sa.String(length=255), nullable=True),
    sa.Column('result', sa.String(length=255), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['header_id'], ['semi_finished_coa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formulation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formulation_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(length=20), nullable=True),
    sa.Column('material_code', sa.String(length=50), nullable=True),
    sa.Column('material_name', sa.String(length=255), nullable=True),
    sa.Column('ratio', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['formulation_id'], ['formulations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('name_ko', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('cas_no', sa.String(length=50), nullable=True),
    sa.Column('composition_ratio', sa.Float(), nullable=True),
    sa.Column('function', sa.String(length=100), nullable=True),
    sa.Column('ewg_grade', sa.String(length=10), nullable=True),
    sa.Column('ewg_data', sa.Text(), nullable=True),
    sa.Column('hs_code', sa.String(length=50), nullable=True),
    sa.Column('nmpa_reg_num', sa.String(length=100), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_formulations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_formulation_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('production_code', sa.String(length=50), nullable=True),
    sa.Column('lab_no', sa.String(length=50), nullable=True),
    sa.Column('revision', sa.String(length=50), nullable=True),
    sa.Column('base_weight_g', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('items_snapshot', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_formulation_id'], ['formulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_packages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('formulation_id', sa.Integer(), nullable=True),
    sa.Column('production_formulation_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('revision', sa.String(length=50), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ingredient_snapshot', sa.Text(), nullable=True),
    sa.Column('quotation_snapshot', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['formulation_id'], ['formulations.id'], ),
    sa.ForeignKeyConstraint(['production_formulation_id'], ['production_formulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('production_formulation_id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=True),
    sa.Column('production_date', sa.Date(), nullable=True),
    sa.Column('lot_no', sa.String(length=100), nullable=True),
    sa.Column('quantity_g', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('specific_gravity', sa.String(length=50), nullable=True),
    sa.Column('viscosity_initial', sa.String(length=50), nullable=True),
    sa.Column('viscosity_next_day', sa.String(length=50), nullable=True),
    sa.Column('ph_initial', sa.String(length=50), nullable=True),
    sa.Column('ph_next_day', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['production_formulation_id'], ['production_formulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('production_formulation_id', sa.Integer(), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(length=50), nullable=True),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('temperature', sa.String(length=50), nullable=True),
    sa.Column('time_min', sa.Float(), nullable=True),
    sa.Column('rpm', sa.String(length=50), nullable=True),
    sa.Column('equipment', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['production_formulation_id'], ['production_formulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('attachment_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['document_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_package_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['document_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_package_links')
    op.drop_table('document_attachments')
    op.drop_table('production_steps')
    op.drop_table('production_runs')
    op.drop_table('document_packages')
    op.drop_table('production_formulations')
    op.drop_table('ingredients')
    op.drop_table('formulation_items')
    op.drop_table('semi_finished_coa_items')
    op.drop_table('materials')
    op.drop_table('ingredient_report_items')
    op.drop_table('formulations')
    op.drop_table('finished_product_coa_items')
    op.drop_table('deletion_requests')
    op.drop_table('users')
    op.drop_table('semi_finished_coa')
    op.drop_table('product_code_rules')
    op.drop_table('ingredient_reports')
    op.drop_table('finished_product_coa')
    op.drop_table('clients')
    # ### end Alembic commands ###
